# Generated by Django 6.1 on 2026-08-22 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=50, verbose_name='გვარი')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ელ-ფოსტა')),
                ('department', models.CharField(max_length=100, verbose_name='დეპარტამენტი')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='კურსის დასახელება')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
                ('credits', models.PositiveIntegerField(default=3, verbose_name='კრედიტები')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='project1.lecturer', verbose_name='ლექტორი')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=50, verbose_name='გვარი')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ელ-ფოსტა')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='რეგისტრაციის თარიღი')),
                ('courses', models.ManyToManyField(blank=True, related_name='students', to='project1.course', verbose_name='კურსები')),
            ],
        ),
    ]
