# Generated by Django 6.1 on 2026-08-22 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='კატეგორიის სახელი')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='პროდუქტის დასახელება')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('has_discount', models.BooleanField(default=False, verbose_name='აქვს ფასდაკლება (SALE)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ფასდაკლებული ფასი')),
                ('is_available', models.BooleanField(default=True, verbose_name='ხელმისაწვდომია')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='დამატების თარიღი')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='კატეგორია')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
